### ISSUE TITLE
Report non-POSIX paths

### ISSUE THREAD

**Issue by e3krisztian** [onekey-sec/unblob#482] opened 2022-12-14 14:22 UTC
Under UNIX file names can be arbitrary byte strings, but of course they are usually valid ASCII/Unicode.

An example archive containing non-POSIX paths is https://github.com/python/cpython/blob/main/Lib/test/testtar.tar : extracting it will yield some interesting files (e.g. `ustar/umlauts-*`, which are just encoded in iso8859-1, instead of UTF-8).

These files are currently skipped over by unblob almost silently (logged as warnings). To be able to collect these paths later `TaskResult.reports` should also get a report about non-POSIX paths.

**Comment by kukovecz** [comment] 2023-04-03 10:53
https://github.com/onekey-sec/unblob/pull/545 Is somewhat trying to solve this. In there, there is a `StatReport` generated for EVERY file, even the ones which are non-POSIX. 

I don't know what is the expected outcome here, is that pull request enoguh? If so, this Issue can be solved. 
If not, discuss here what is the expected behavior (a new report type for non-posix paths? A new report type for not skipped Tasks with reason?)

**Comment by kukovecz** [comment] 2023-04-05 12:24
Since #547 is merged (with #548), this is no longer needed as unblob is processing files with non-POSIX paths so they will have the reports.

**Closed as completed by kukovecz** 2023-04-05 12:24 UTC
