### ISSUE TITLE
Binary Installation 

### ISSUE THREAD

**Issue by bluusun** [onekey-sec/unblob#493] opened 2023-01-19 15:16 UTC
Am I missing that? Any package managers? apt-get/brew/pip?

**Comment by QKaiser** [comment] 2023-01-20 10:15
We're currently providing a [Nix](https://nixos.org/) package. We plan on building Debian packages and push python wheels to PyPi in the future once we have proper versioning in place, but it's not high priority to us at the moment.

**Comment by kissgyorgy** [comment] 2023-01-24 12:49
Dupe of #102, can be closed. I quick search would have revealed that issue.

**Closed** 2023-01-24 12:59 UTC
Labels: duplicate, question
